services:
  api:
    # build: .
    image: nishan9848/summer-project:latest
    expose:
      - "8000"

  nginx:
    image: nishan9848/nginx-summer:latest
    ports:
      - "80:80"
    #volumes:
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
